# Generated by Django 3.1.3 on 2021-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20210302_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='text',
            field=models.CharField(default='Forgot to write smth', max_length=2048),
        ),
    ]
