# Generated by Django 3.1.3 on 2021-03-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_thread_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='number',
        ),
        migrations.AlterField(
            model_name='thread',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.thread'),
        ),
    ]
