# Generated by Django 3.1.3 on 2021-03-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20210302_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.thread'),
        ),
    ]
